on: workflow_dispatch
jobs:
  coverage:
    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
        reuse-go: true
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'
      continue-on-error: true -m coverage report'