on: workflow_dispatch

jobs:
  coverage:
    strategy:
      matrix:
        go: [ '1.19' ]
        platform: [ ubuntu-latest ] # can not run in windows OS
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Test
      run: go test -v ./...

    - name: Go coverage report
      uses: ncruces/go-coverage-report@v0.2.7
      with:
        report: true
        chart: true
        amend: true
        reuse-go: true
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'
      continue-on-error: true